config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'info', to: 'welcome#info'
  get 'contact', to:'welcome#contact'
  get 'all',to: 'categories#all'
  get 'dashboard', to: 'welcome#dashboard'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name_category , presence: true
	has_many :has_categories
	has_many :products, through: :has_categories
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :has_categories
	has_many :categories, through: :has_categories
	after_create :save_categories

	has_attached_file(:picture,
      styles: {medium: "600x400", thumb: "300x200"},
      default_url: "/images/:style/missing_product.png",
      default_style: :medium,
      :storage => :s3,
      :path => "/images/products/product_:product_id/:style/product.:extension"
 )
 	Paperclip.interpolates :product_id  do |attachment, style|
	 attachment.instance.id
 	end
  validates_attachment_content_type :picture, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png)$/, :message => 'file type is not allowed (only jpeg/png/jpg images)'
	validates_attachment_size :picture, :in => 0.megabytes..1.megabytes

 	def categories=(value)
 		@categories = value
 	end



 	private

 	def save_categories
 		@categories.each do |category_id|
 			HasCategory.create(category_id: category_id, product_id: self.id)
 		end
 	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file( :avatar,
      styles: {medium: "300x300", thumb: "100x100"},
      default_url: "/images/:style/missing.jpg",
      default_style: :medium,
      :storage => :s3,
      :path => "/images/users/user_:user_id/:style/avatar.:extension"
 )
  Paperclip.interpolates :user_id  do |attachment, style|
    attachment.instance.id
  end
  validates_attachment_content_type :avatar, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png)$/, :message => 'file type is not allowed (only jpeg/png/jpg images)'
  validates_attachment_size :avatar, :in => 0.megabytes..1.megabytes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_categories

  private

  def set_categories
  	@Categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end
  def all
    @categories = Category.all
  end
  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name_category, :color)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.categories = params[:categories]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params) && @product.categories = params[:categories]
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:titulo, :desc_corta, :desc, :precio, :precio_compra, :tipo, :marca, :modelo, :stock, :picture, :categories)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @products = Product.new
    @categories = Category.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_category %>
    <%= f.text_field :name_category %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/all.html.erb
<% @categories.each do |category|%>
  <h2><%= category.name_category %></h2>
  <div class="row">
      <% category.products.each do |product| %>
          <%= link_to  product,class: 'col-md-4' do %>
            <%= image_tag(product.picture.url('medium'), class: "img-responsive") %>
            <p><%= product.titulo %></p>
            <p><%= product.desc_corta %></p>
          <%end%>
        
      <%end%>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name category</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name_category %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h2><%= @category.name_category %></h2>
<div class="row">
		<% @category.products.each do |product| %>
				<%= link_to  product,class: 'col-md-4' do %>
					<%= image_tag(product.picture.url('medium'), class: "img-responsive") %>
					<p><%= product.titulo %></p>
					<p><%= product.desc_corta %></p>
				<%end%>
		<%end%>
</div>

<p id="notice"><%= notice %></p>
<!--<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChoroStore</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Roboto+Mono:300,300i,400,400i,500,500i,700,700i|Roboto+Slab:300,400,700|Roboto:300,300i,400,400i,500,500i,700,700i&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css" type="text/css" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "style" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid no-padding">
      <header>
        <%= link_to image_tag("/images/logo2.png", class: "img-responsive") , root_path , class: "set-logo"%>
        <nav>
          <%= link_to info_path, :class => 'btn-nav' do %>
            <i class="fa fa-home" aria-hidden="true"></i>
            <span class="hide-on-small-mobile ml-3">Quienes Somos</span>
          <% end %>
          <%= link_to all_path, :class => 'btn-nav' do %>
            <i class="fa fa-home" aria-hidden="true"></i>
            <span class="hide-on-small-mobile ml-3">Catalogo</span>
          <% end %>

          <%= link_to contact_path, :class => 'btn-nav' do %>
            <i class="fa fa-home" aria-hidden="true"></i>
            <span class="hide-on-small-mobile ml-3">Contacto</span>
          <% end %>

          <% unless user_signed_in? %>
            <%= link_to new_user_session_path, :class => 'btn-nav' do %>
              <i class="fa fa-user" aria-hidden="true"></i>
              <span class="hide-on-small-mobile ml-3">Log In</span>
            <% end %>
            <%= link_to new_user_registration_path, :class => 'btn-nav' do %>
              <i class="fa fa-user-plus" aria-hidden="true"></i>
              <span class="hide-on-small-mobile ml-3">New User</span>
            <% end %>
          <% else %>
            <%= link_to destroy_user_session_path, :class =>  'btn-nav', :method => :delete do %>
              <i class="fa fa-user-o" aria-hidden="true"></i>
              <span class="hide-on-small-mobile ml-3">Log Out</span>
            <% end %>
          <%end%>
        </nav>
      </header>
      <aside >
        <ul >
          <% @Categories.each do |category| %>
          <li><%= link_to category.name_category, category, class:'btn' %></li>
          <% end %>
        </ul>
      </aside>
      <div class="content-col">
        <%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
  </div>
  <footer class=" col-md-12 center text-center">
    <div class="">
      <p> Keilabs ®2017</p>
    </div>
  </footer>
  </body>

</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :desc_corta %>
    <%= f.text_field :desc_corta %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.text_field :precio %>
  </div>

  <div class="field">
    <%= f.label :precio_compra %>
    <%= f.text_field :precio_compra %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :marca %>
    <%= f.text_field :marca %>
  </div>

  <div class="field">
    <%= f.label :modelo %>
    <%= f.text_field :modelo %>
  </div>

  <div class="field">
    <%= f.label :stock %>
    <%= f.number_field :stock %>
  </div>

  <div class="field">
    <label> Categorias </label>
    <% @categories.each do |cat| %>
      <div class="field">
        <%= check_box_tag "categories[]" ,cat.id %> <%= cat.name_category %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Desc corta</th>
      <th>Desc</th>
      <th>Precio</th>
      <th>Tipo</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.titulo %></td>
        <td><%= product.desc_corta %></td>
        <td><%= product.desc %></td>
        <td><%= product.precio %></td>
        <td><%= product.tipo %></td>
        <td><%= product.marca %></td>
        <td><%= product.modelo %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
  <div class="row product-img">
    <span>
        <%=image_tag @product.picture.url,class: 'img-responsive' %>
    </span>
  </div>
  <div class="product-detail">
    <h1 class="product-title"><%= @product.titulo %> </h1>

    <% @product.categories.each do |cat| %>
      <i><%= link_to  cat.name_category ,cat ,class: 'cat-link' %></i>
    <%end%>
    <p class="product-desc"><%= @product.desc %></p>
    <p> Valor: <%= @product.precio %> - Disponibles: <%= @product.stock %></p>

  </div>

app/views/welcome/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_category %>
    <%= f.text_field :name_category %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :desc_corta %>
    <%= f.text_field :desc_corta %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>

  <div class="field">
    <%= f.label :product %>
    <%= f.file_field :product %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.text_field :precio %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :marca %>
    <%= f.text_field :marca %>
  </div>

  <div class="field">
    <%= f.label :modelo %>
    <%= f.text_field :modelo %>
  </div>

  <div class="field">
    <%= f.label :stock %>
    <%= f.number_field :stock %>
  </div>

  <div class="field">
    <label> Categorias </label>
    <% @categories.each do |cat| %>
      <div class="field">
        <%= check_box_tag "categories[]" ,cat.id %> <%= cat.name_category %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/contact.html.erb
<h1>hello!!</h1>

app/views/welcome/dashboard.html.erb
<h2>Agregar Nuevo Producto</h2>

app/views/welcome/index.html.erb
<%if user_signed_in?%>
	<h1>hola <%= current_user.name %></h1>
	<%= image_tag current_user.avatar.url %>
<%end%>

app/views/welcome/info.html.erb
<div class="row">
  <div class="info-title">
    <h1>Foristería Cynthia</h1>
  </div>
  <div class="center-md">
    <%= image_tag "http://floristeriacynthia.cl/imagenes/flor_baner.jpg", class: "img-responsive"%>
  </div>
  <div class="desc">
    <p>
      Somos una empresa familiar que nació hace mas de 30 años, lo que nos ha otorgado una experiencia relevante en el rubro, aportando a nuestros clientes soluciones y asesorías que contemplan el diseño, realización de arreglos florares y soluciones de decoración para distintas ocasiones. Contamos con una gran variedad de flores naturales nacionales e importadas, las cuales según el motivo, acompañamos con accesorios de excelente calidad. Ofrecemos arreglos personalizados con las preferencias que nos indiquen, además de decoración de oficinas, iglesias y salones de eventos.</br>

    Ofrecemos un servicio integral de solicitud y despacho de nuestros arreglos con el fin de hacerles más cómoda e informada la elección de su pedido. </br>

    El despacho a domicilio está incluido en el valor total del producto, acotado por un cierto un radio de envío, lo cual debe ser previamente consultado.</br>

    También tenemos despacho a todo el país.
    </p>
  </div>

</div>